services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xo2hive-core
    image: xo2hive-core:latest
    environment:
      - CORE_CONFIG=/app/config.yaml
    networks:
      xo2hive:
        ipv4_address: 172.30.0.2
    ports:
      - "50051:50051"
    restart: unless-stopped
    # Optional: Lokale config überschreiben via Bind-Mount
    volumes:
       - ./config.yaml:/app/config.yaml:ro

    # logging-driver prüfen (Standard ist ok):
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  xo2hive:
    external: true
