// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: core/v1/realtime.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame ist das universelle Datenpaket. Es ist absichtlich generisch gehalten, damit
// beliebige Plugins/Clients es für eigene Zwecke nutzen können.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Typ des Frames (z. B. "HELLO", "EVENT", "PUBLISH").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Absender-ID (wird i. d. R. vom Core vergeben). Kann leer sein bei der ersten Nachricht.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Ziel-ID. Leer = Broadcast an alle außer Absender.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Freies Topic-Feld zur logischen Gruppierung.
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// Nutzdaten als Bytes (z. B. JSON-kodiert).
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Sequenznummer (optional nutzbar durch Clients).
	Seq uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	// Unix-Timestamp in Millisekunden, gesetzt vom Client oder Core.
	TsUnixMs int64 `protobuf:"varint,7,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	// Beliebige Metadaten als Key/Value.
	Meta          map[string]string `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_core_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_core_v1_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Frame) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Frame) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Frame) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Frame) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *Frame) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_core_v1_realtime_proto protoreflect.FileDescriptor

const file_core_v1_realtime_proto_rawDesc = "" +
	"\n" +
	"\x16core/v1/realtime.proto\x12\acore.v1\"\x86\x02\n" +
	"\x05Frame\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\a \x01(\x03R\btsUnixMs\x12,\n" +
	"\x04meta\x18\b \x03(\v2\x18.core.v1.Frame.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x0129\n" +
	"\bRealtime\x12-\n" +
	"\aConnect\x12\x0e.core.v1.Frame\x1a\x0e.core.v1.Frame(\x010\x01B\x12Z\x10proto/core/v1;v1b\x06proto3"

var (
	file_core_v1_realtime_proto_rawDescOnce sync.Once
	file_core_v1_realtime_proto_rawDescData []byte
)

func file_core_v1_realtime_proto_rawDescGZIP() []byte {
	file_core_v1_realtime_proto_rawDescOnce.Do(func() {
		file_core_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_realtime_proto_rawDesc), len(file_core_v1_realtime_proto_rawDesc)))
	})
	return file_core_v1_realtime_proto_rawDescData
}

var file_core_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_realtime_proto_goTypes = []any{
	(*Frame)(nil), // 0: core.v1.Frame
	nil,           // 1: core.v1.Frame.MetaEntry
}
var file_core_v1_realtime_proto_depIdxs = []int32{
	1, // 0: core.v1.Frame.meta:type_name -> core.v1.Frame.MetaEntry
	0, // 1: core.v1.Realtime.Connect:input_type -> core.v1.Frame
	0, // 2: core.v1.Realtime.Connect:output_type -> core.v1.Frame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_realtime_proto_init() }
func file_core_v1_realtime_proto_init() {
	if File_core_v1_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_realtime_proto_rawDesc), len(file_core_v1_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_realtime_proto_goTypes,
		DependencyIndexes: file_core_v1_realtime_proto_depIdxs,
		MessageInfos:      file_core_v1_realtime_proto_msgTypes,
	}.Build()
	File_core_v1_realtime_proto = out.File
	file_core_v1_realtime_proto_goTypes = nil
	file_core_v1_realtime_proto_depIdxs = nil
}
